services:
  backend:
    container_name: mbus_backend
    build:
      context: ./apps/bus-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_ADDR: ${REDIS_ADDR}
      ORS_API_KEY: ${ORS_API_KEY}

  frontend:
    container_name: mbus_frontend
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - frontend
        - backend