services:
  db:
    image: postgres:16
    container_name: mbus_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mbus_redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redisdata:/data

  backend:
    container_name: mbus_backend
    build:
      context: ./apps/bus-service
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_ADDR: ${REDIS_ADDR}
      ORS_API_KEY: ${ORS_API_KEY}

  frontend:
    container_name: mbus_frontend
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - frontend
        - backend

volumes:
  pgdata:
  redisdata: