name: Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-bus-service:
    name: Build Bus Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/bus-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Go app
        run: go build ./...

  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
